image: "node:10"

before_script:
  - ./scripts/before.sh

stages:
  - lint
  - deploy

lint:
  script: "./scripts/lint.sh"
  stage: "lint"

deploy:
  script: "./scripts/deploy.sh"
  stage: "deploy"
  when: "manual"