AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for creating the cloudformation execution user"
Resources:
  CloudformationUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: "{{resolve:ssm-secure:iam-cloudformation-execution-user-CloudformationUserPassword:1}}"
        PasswordResetRequired: true
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/job-function/ViewOnlyAccess"]
      Policies:
        - PolicyName: CloudformationExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ["cloudformation:*"]
                Resource: "*"
              - Effect: Allow
                Action: ["iam:PassRole"]
                Resource: !Sub "${CloudformationAssumeRole.Arn}"
  CloudformationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 0
      Status: Active
      UserName: !Sub "${CloudformationUser}"
  CloudformationAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["cloudformation.amazonaws.com"]
            Action: ["sts:AssumeRole"]
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

Outputs:
  CloudformationUsername:
    Description: Cloudformation Username
    Value: !Sub "${CloudformationUser}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudformationUsername"
  CloudformationUserAccessKeyId:
    Description: Cloudformation User Access Key Id
    Value: !Sub "${CloudformationUserAccessKey}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudformationUserAccessKeyId"
  CloudformationUserAccessKeySecret:
    Description: Cloudformation User Access Key Secret
    Value: !Sub "${CloudformationUserAccessKey.SecretAccessKey}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudformationUserAccessKeySecret"
  CloudformationAssumeRoleArn:
    Description: Cloudformation Assume Role ARN
    Value: !Sub "${CloudformationAssumeRole.Arn}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudformationAssumeRoleArn"
